language: ruby
#sudo: false
addons:
  apt:
    packages:
    - libicu-dev
    - libicu48
before_install: script/travis/before_install
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode
  - jruby-22mode
notifications:
  disabled: true
git:
  submodules: false
cache: bundler
